# Site settings
title: mcTLS
email: dnaylor@cs.cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  Resources related to the multi-context TLS (mcTLS) protocol.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mctls.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
